repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: check-added-large-files
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: filename-convention
        name: Filename Convention
        entry: ./scripts/check_filenames.sh
        language: script
        files: .*
